controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

inicio:
    path: /
    controller: App\Controller\MainController::bienvenida